baseURL: "https://pages.ruofeng.me/"
languageCode: zh
title: Ruofeng's Blog
theme: hugo-theme-cactus
author: Ruofeng Lei
pygmentsStyle: tango
pygmentsCodeFences: true
permalinks:
  posts: "/:year/:month/:day/:slug/"
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 100
    - identifier: about
      name: About
      title: about section
      url: /about/
    - identifier: tags
      name: Tags
      url: /tags/
params:
  description: >-
    Hi, I’m a theme for the **Hugo** blogging framework. I’m particularly great
    for a personal web page with a simple blog. In this paragraph, you can
    provide some information about yourself. Below, you’re most recent or
    highlighted writings and projects are listed.
