baseURL: "https://pages.ruofeng.me/"
languageCode: zh
title: Ruofeng's Blog
theme: hugo-theme-cactus
author: Ruofeng Lei
pygmentsStyle: tango
pygmentsCodeFences: true
permalinks:
  posts: "/:year/:month/:day/:slug/"
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 100
    - identifier: about
      name: About
      title: about section
      url: /about/
    - identifier: tags
      name: Tags
      url: /tags/
params:
  utterancesRepo: abowloflrf/blog
  description: >-
    Place I write.
